version: "3.8"

volumes: 
  pgdata_auth:

services:

  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_auth:/var/lib/postgresql/data"
    command: ["postgres", "-c", "log_statement=all"]

  migrate:
    container_name: migrator
    image: migrate/migrate
    volumes:
      - ./account/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@database:5432/users?sslmode=disable", "up"]
    links: 
      - database