GET http://localhost/api/account/me
Authorization: Bearer replace_me_with_accessToken

###
POST http://localhost/api/account/signup
Content-Type: application/json

{
    "login": "alice",
    "password": "alicePass"
}

###
POST http://localhost/api/account/signin
Content-Type: application/json

{
    "login": "alice",
    "password": "alicePass"
}

###
POST http://localhost/api/account/signout
Authorization: Bearer replace_me_with_accessToken

###
POST http://localhost/api/account/tokens
Content-Type: application/json

{
    "refreshToken": "replace_me_with_refresh_token"
}

###
POST http://localhost/api/account/image

###
DELETE  http://localhost/api/account/image

###
PUT  http://localhost/api/account/details
Authorization: Bearer replace_me_with_accessToken
Content-Type: application/json

{
    "name": "Alice",
    "email": "alice@mail.com",
    "website": "https://www.alice.com"
}