GET http://localhost/api/account/me
Authorization: Bearer {replace me with accessToken}

###
POST http://localhost/api/account/signup
Content-Type: application/json

{
    "login": "alice",
    "password": "alicePass"
}

###
POST http://localhost/api/account/signin
Content-Type: application/json

{
    "login": "alice",
    "password": "alicePass"
}

###
POST http://localhost/api/account/signout

###
POST http://localhost/api/account/tokens
Content-Type: application/json

{
    "refreshToken": "{replace me with refreshToken"
}

###
POST http://localhost/api/account/image

###
DELETE  http://localhost/api/account/image

###
PUT  http://localhost/api/account/details